### ISSUE TITLE
I downloaded and installed linux bash profile and it completely changed my terminal. How do I switch back to the profile I had before?

### ISSUE THREAD

**Issue by fbagirov** [learn-co-curriculum/swift-welcome#6]
I downloaded and installed a bash profile in my linux command line:

curl https://raw.githubusercontent.com/flatiron-school/dotfiles/master/.bash_profile -o ~/.bash_profile
source ~/.bash_profile
xcode-select --install
Now it is not finding the commands and packages I've used before.

I am also learning other tools, and I need to have it restored. What is the way to "undo" the changes?

Going forward, can I create a virtual environment and install the bash profile for this class in that virtual environment?

**Comment by JimCampagno** [comment]
When you run that command, it will make a back-up for you before making any changes.

To restore to that back-up, run the following commands:

``` swift
rm ~/.bash_profile
mv ~/.bash_profile.bak ~/.bash_profile
```

Let me know if that works for you! As far as setting up a virtual environment--I'm not entirely sure, I can do some research for you, have you been able to find anything?

@fbagirov
