### ISSUE TITLE
source ~/.bash_profile doesn't work for who installed zsh on terminal

### ISSUE THREAD

**Issue by Janatbek** [learn-co-curriculum/swift-welcome#8]
I run this `source ~/.bash_profile` command and didn't work telling  `couldn't find bind.`
so I googled and on stackoverflow I found that if you have zsh installed I shouldn't have to run `source ~/.bash_profile`
so I run `source ~/.zshrc`
Is that right?
I think you should update readme with any error.

**Comment by Janatbek** [comment]
I would like to update platform to:
if you have zsh installed on your machine you have to run `exec bash` then run `source ~/.bash_profile` .
because I had error before. and found that my error was that I was using zsh not bash and it couldn't find command `bind`.
please correct my comment I can't explain in english very well.

**Comment by Janatbek** [comment]
Now my terminal looks exactly like on platform. thanks

**Comment by JimCampagno** [comment]
@Janatbek Thanks for the feedback, this is great. I just made the changes to help out any future students.
